### ISSUE TITLE
gpkg_data_columns must have a column "name" with a unique key 

### ISSUE THREAD

**Issue by fjlopez** [ngageoint/geopackage-core-java#45]
#### Version Information:

  * GeoPackage Core Java Version: 3.3.0 (and develop and master)

#### Expected:

  * [Requirement 103 (GeoPackage 1.1.0+)](http://www.geopackage.org/spec121/index.html#r103): [The column `name` shall have a key unique](http://www.geopackage.org/spec121/index.html#gpkg_data_columns_cols)  

#### Observed:

  * The column `name` of `gpkg_data_columns` is not unique. The ORM annotation does not enforce uniqueness.

#### Relevant Code:

https://github.com/ngageoint/geopackage-core-java/blob/dfe72e311d21b18640ff078db77e69c6ca2a6870/src/main/java/mil/nga/geopackage/schema/columns/DataColumns.java#L97-L101

**Comment by bosborn** [comment]
The name was made unique in opengeospatial/geopackage#183 and opengeospatial/geopackage#184.  

One table should not be able to claim a "human-readable identifier (e.g. short name)" preventing other tables from using the same value.  This is described in opengeospatial/geopackage#487.

This was fixed in opengeospatial/geopackage#492 and [here](https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/resources/sql/gpkg_data_columns).

**Comment by bosborn** [comment]
It is fixed in the current (working) spec [here](http://www.geopackage.org/spec/index.html#gpkg_data_columns_sql), but needs a pull request for [here](http://www.geopackage.org/spec/index.html#gpkg_data_columns_cols).

**Comment by bosborn** [comment]
Created pull request opengeospatial/geopackage#497

**Comment by fjlopez** [comment]
Good work!
