### ISSUE TITLE
convert x and y to lat and long

### ISSUE THREAD

**Issue by swkasi535** [ngageoint/geopackage-core-java#47]
I am implementing the decoding of a blob field,

for that I have used fromBytes method in  [https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/java/mil/nga/geopackage/geom/GeoPackageGeometryData.java](url)

I got the geometry object and it contains geometryType, x and y coordinates.

Based on this I want to convert the X and Y to lat and long.

**Comment by bosborn** [comment]
The X and Y are the lat and long in the projection they are stored as.  To get these as WGS84 or another projection, you'd have to transform them.  The geometry might have a valid spatial reference (srs) id that you can pull from the GeoPackageGeometryData.  Otherwise you can use the srs id from the feature table's GeometryColumns entry.  The SpatialReferenceSystem contains an organization and an organization coordsys id value, which can be retrieved as a projection.

```
// GeoPackageGeometryData geometryData = ...

Geometry geometry = geometryData.getGeometry();
long srsId = geometryData.getSrsId();

SpatialReferenceSystemDao srsDao = geoPackage
		.getSpatialReferenceSystemDao();
SpatialReferenceSystem srs = srsDao
		.queryForId(srsId);
Projection srsProjection = srs.getProjection();

// OR if you know blob's feature table origination, geometry columns from the feature dao or queried
// Projection srsProjection = geometryColumns.getProjection();

ProjectionTransform toWgs84 = srsProjection
		.getTransformation(
				ProjectionConstants.EPSG_WORLD_GEODETIC_SYSTEM);

Geometry wgs84Geometry = toWgs84.transform(geometry);
//Point wgs84Point = toWgs84.transform(point);
//double[] wgs84Coordinate = toWgs84.transform(x, y);
```
